import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import Providers from '@/context/Providers'
import AsideMenuOptions from '@/components/sidebar/AsideMenuOptions'
import { MainNav } from '@/components/sidebar/MainNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <MainNav />
            <div className='sm:container flex-1 items-start md:grid md:grid-cols-[180px_minmax(0,1fr)] md:gap-4 lg:grid-cols-[200px_minmax(0,1fr)]'>
                <aside className='z-30 -ml-2 hidden h-[calc(100vh-3.5rem)] w-full shrink-0 md:sticky md:block border-r-[0.1px]'>
                    <AsideMenuOptions />
                </aside>
                <main className='py-6'>
                    {children}
                </main>
            </div>
        </>
    )
}
